use crate::cert::OutCert;
use crate::csr::OutCSR;
use crate::error::CborCertError;
use crate::keygen::OutKeyPair;
use itertools::Itertools;
use std::fs;

pub trait Saving {
    fn save(&self) -> Result<(), CborCertError>;
}

pub enum Out<'a> {
    OutKeyPair(OutKeyPair<'a>),
    OutCSR(OutCSR<'a>),
    OutCert(OutCert<'a>),
}

impl Saving for Out<'_> {
    fn save(&self) -> Result<(), CborCertError> {
        match self {
            Out::OutKeyPair(ed25519_data) => ed25519_data.save(),
            Out::OutCSR(csr_data) => csr_data.save(),
            Out::OutCert(cert_data) => cert_data.save(),
        }
    }
}

#[derive(Debug, PartialEq)]
pub enum FileFormat {
    C,
    DER,
    TOML,
}
pub struct File {
    pub full_name: String,
    pub name: String,
    pub format: FileFormat,
}

const C_HEADER: &str = "/*
    This file is automatically generated with cborcert.   
 ";
const KEY_META: &str = "
    It contains a signature key.
*/\n\n";
const CSR_META: &str = "
    It contains a Certificate Signing Request (CSR).
*/\n\n";
const CERT_META: &str = "
    It contains a Certificate.
*/\n\n";

impl Saving for OutKeyPair<'_> {
    fn save(&self) -> Result<(), CborCertError> {
        for file in self.out_files {
            match &file.format {
                FileFormat::C => {
                    fs::write(
                        format!("{}_{}.c", file.name, self.alg_pk_name),
                        format!(
                            "{}{}const char sk []= {{ {:#04x} }};\n\nconst char pk []=  {{ {:#04x} }};\n\nconst unsigned int sk_len = sizeof(sk);\n\nconst unsigned int pk_len = sizeof(pk);",
                            C_HEADER,
                            KEY_META,
                            self.key_pair.sk.iter().format(", "),
                            self.key_pair.pk.iter().format(", ")
                        ),
                    )?;
                }
                FileFormat::TOML => {
                    return Err(CborCertError::KeyCannotBeSavedInTomlFile);
                }
                FileFormat::DER => {
                    fs::write(
                        format!("{}_sk_{}.der", file.name, self.alg_pk_name),
                        &self.key_pair.sk,
                    )?;
                    fs::write(
                        format!("{}_pk_{}.der", file.name, self.alg_pk_name),
                        &self.key_pair.pk,
                    )?;
                }
            }
        }
        Ok(())
    }
}

impl Saving for OutCSR<'_> {
    fn save(&self) -> Result<(), CborCertError> {
        for file in self.out_files {
            match &file.format {
                FileFormat::C => {
                    fs::write(
                        format!("{}.c", file.name),
                        format!(
                            "{}{}const char csr []= {{ {:#04x} }};\n\nconst unsigned int csr_len = sizeof(csr);",
                            C_HEADER,
                            CSR_META,
                            self.csr.iter().format(", "),
                        ),
                    )?;
                }
                FileFormat::TOML => {
                    return Err(CborCertError::CSRCannotBeSavedInTomlFile);
                }
                FileFormat::DER => {
                    println!("file.name {}:", file.name);
                    fs::write(format!("{}.der", file.name), &self.csr)?;
                }
            }
        }
        Ok(())
    }
}

impl Saving for OutCert<'_> {
    fn save(&self) -> Result<(), CborCertError> {
        for file in self.out_files {
            match &file.format {
                FileFormat::C => {
                    fs::write(
                        file.full_name.to_string(),
                        format!(
                            "{}{}const char cert []= {{ {:#04x} }};\n\nconst unsigned int cert_len = sizeof(cert);",
                            C_HEADER,
                            CERT_META,
                            self.cert.iter().format(", "),
                        ),
                    )?;
                }
                FileFormat::TOML => {
                    return Err(CborCertError::CSRCannotBeSavedInTomlFile);
                }
                FileFormat::DER => {
                    println!("file.name {}:", file.name);
                    fs::write(file.full_name.to_string(), &self.cert)?;
                }
            }
        }
        Ok(())
    }
}
